# Site settings
title: Nick Jacob
email: me@nickjacob.com
description: "when I close my eyes I see code"
baseurl: ""
url: "http://nickjacob.com"
twitter_username: nickjacob
github_username:  nickjacob

# Build settings
markdown: kramdown
permalink: pretty
