# Site settings
title: Nick Jacob
email: me@nickjacob.com
description: "Engineer, coder. The kind of masochist who knows how to google."
baseurl: ""
url: "http://nickjacob.com"
twitter_username: nickjacob
github_username:  nickjacob

# Build settings
markdown: kramdown
permalink: pretty
